<?xml version="1.0" encoding="UTF-8"?>
<log>
<entry date="Fri Nov 30 16:05:25 EST 2001">
  <status id="org.eclipse.xyz.SomePlugin" sev="ERROR" msg="The Foo operation failed to complete." code="1">
    <status id="org.eclipse.xyz.AnotherPlugin" sev="WARNING" msg="An internal error occurred while attempting to foo." code="1">
      <exception message="null" trace="
java.lang.NullPointerException
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.getInterestingStatuses(LogSerializationTest.java:97)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.getInterestingMultiStatuses(LogSerializationTest.java:73)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.testMultiStatus(LogSerializationTest.java:161)
	at java.lang.reflect.Method.invoke(Native Method)
	at junit.framework.TestCase.runTest(TestCase.java:166)
	at junit.framework.TestCase.runBare(TestCase.java:140)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:131)
	at junit.framework.TestSuite.runTest(TestSuite.java:173)
	at junit.framework.TestSuite.run(TestSuite.java:168)
	at junit.textui.TestRunner.doRun(TestRunner.java:74)
	at junit.textui.TestRunner.run(TestRunner.java:200)
	at org.eclipse.core.tests.harness.EclipseTestHarnessApplication.run(EclipseTestHarnessApplication.java:142)
	at org.eclipse.core.tests.harness.EclipseTestHarnessApplication.run(EclipseTestHarnessApplication.java:138)
	at org.eclipse.core.tests.harness.EclipseTestHarnessApplication.run(EclipseTestHarnessApplication.java:120)
	at org.eclipse.core.internal.boot.InternalBootLoader.run(InternalBootLoader.java:820)
	at org.eclipse.core.boot.BootLoader.run(BootLoader.java:285)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.eclipse.core.launcher.Main.basicRun(Main.java:151)
	at org.eclipse.core.launcher.Main.run(Main.java:502)
	at org.eclipse.core.tests.harness.launcher.Main.main(Main.java:91)
	at com.dj.RunTests.main(RunTests.java:46)
">
      </exception>
    </status>
  </status>
</entry>
</log>
